version: 0.0
os: linux
files:
  - source: server
    destination: /var/www/flask/server
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/configure_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root